# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expand-reduce-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expand-reduce-app
  template:
    metadata:
      labels:
        app: expand-reduce-app
    spec:
      containers:
        - name: expand-reduce-container
          image: uniflow-hanliao:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
