# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: expand-reduce-service
spec:
  selector:
    app: expand-reduce-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer